# Generated by Django 5.2.5 on 2025-08-22 05:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='cpu_usage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='process',
            name='memory_usage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='process',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
